accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
]

filme/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name="home"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^verwaltung/", include("verwaltung.urls", namespace="verwaltung")),
]

verwaltung/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'verwaltung'

urlpatterns = [
    url(r"uebersicht/$", views.Uebersicht.as_view(),name='uebersicht'),
    url(r"add_film/$", views.CreateFilm.as_view(), name="newfilm"),
    url(r'^film/(?P<pk>\d+)$', views.FilmDetailView.as_view(), name='film_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.FilmUpdateView.as_view(), name='film_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.FilmDeleteView.as_view(), name='film_remove'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return self.username

verwaltung/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Film(models.Model):
    QUALS = (
        ('Kein Eintrag','Kein Eintrag'),
        ('sehr gut','sehr gut'),
        ('gut','gut'),
        ('mittel','mittel'),
        ('schlecht','schlecht'),
    )
    GENRES = (
        ('Comedy','Comedy'),
        ('Horror','Horror'),
        ('Action','Action'),
        ('Fantasy','Fantasy'),
        ('Drama','Drama'),
        ('Adventure','Adventure'),
        ('Sci-fi','Sci-fi'),
        ('Animation','Animation'),
        ('Crime','Crime'),
        ('Mystery','Mystery'),
        ('Romance','Romance'),
    )
    BEWS = (
        ('Keine','Keine'),
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
    )
    titel = models.CharField(max_length=150, unique=True)
    genre = models.CharField(max_length=100,choices=GENRES)
    ort = models.CharField(max_length=200)
    qual = models.CharField(max_length=100,choices=QUALS,default="Kein Eintrag")
    bew = models.CharField(max_length=100,choices=BEWS,default="Keine")
    class Meta:
        ordering = ('-titel',)
    def __str__(self):
        return self.titel
    def get_absolute_url(self):
        return reverse("verwaltung:film_detail",kwargs={'pk':self.pk})

verwaltung/forms.py
from django import forms
from . import models

class FilmForm(forms.ModelForm):
    class Meta():
        model = models.Film
        fields = ('titel','genre','ort','qual','bew')
        widgets = {
            'ort':forms.TextInput(attrs={'placeholder': 'Box 1'}),
        }
        labels = {
            'qual':"Qualitaet",
            'bew':"Bewertung",
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

filme/views.py
from verwaltung.models import Film
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q

def index(request):
    queryset_list = Film.objects.all()
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(Q(titel__icontains=query)|Q(genre__icontains=query)).distinct()
    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {"object_list":queryset, "page": 'page',}
    return render(request, "index.html", context)

verwaltung/views.py
from django.views.generic import TemplateView, CreateView,DetailView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models
from django.urls import reverse_lazy
from django.shortcuts import render,get_object_or_404

class Uebersicht(TemplateView):
    template_name = "verwaltung/test.html"

class CreateFilm(LoginRequiredMixin, CreateView):
    form_class = forms.FilmForm
    model = models.Film
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return super().form_valid(form)

class FilmDetailView(DetailView):
    model = models.Film

class FilmUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'verwaltung/film_detail.html'
    form_class = forms.FilmForm
    model = models.Film

class FilmDeleteView(LoginRequiredMixin,DeleteView):
    model = models.Film
    success_url = reverse_lazy('home')

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Filme</title>
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="{% static "css/master.css" %}" />
    <link rel="stylesheet" href="{% static "filme/css/master.css" %}" />
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <style>
      body{
        background-color: #EDF2F4;
      }
      a{
        color: #097596;
      }
      h1{
        margin-top: 15px;
        margin-left: 30px;
        text-decoration: underline;
      }
      h3, p{
        margin-left: 10px;
      }
      p{
        color: #4e5051;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand mybrand ob" href="{% url 'home' %}">Film-Verwaltung</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link ob" href="{% url 'home' %}">alle Filme</a>
            </li>
            <li class="nav-item">
              <a class="nav-link ob" href="{% url 'verwaltung:newfilm' %}">neuer Film</a>
            </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            {% block oben %}
            {% endblock %}
            <li class="nav-item">
              <a class="nav-link ob" href="{% url 'accounts:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link ob" href="{% url 'accounts:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block head %}
<style>
  .pagination{
    margin-left: 7px;
  }
  .afilm{
    border: solid 1px black;
    width: 70%;
  }
  h3{
    padding-top: 20px;
    padding-left: 20px;
  }
  .pag{
    margin-top: 40px;
    margin-left: auto;
    float: right;
  }
</style>
{% endblock %}
{% block oben %}
<form class="form-inline my-2 my-lg-0" method="get" action="">
  <input name="q" type="text" placeholder="Search..." value="{{ request.GET.q }}">
  <input type="submit" name="" value="Search">
</form>
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="container-fluid">
      <h1>Filme</h1>
      {% for film in object_list %}
        <div class="afilm">
          <h3>Titel: <a href="{% url 'verwaltung:film_detail' pk=film.pk %}">{{ film.titel }}</a></h3>
          <div class="row">
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xl-5">
              <p>Bewertung: {{ film.bew }}</p>
              <p>Genre: {{ film.genre }}</p>
            </div>
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-xl-5">
              <p>Qualitaet: {{ film.qual }}</p>
              <p>Ort: {{ film.ort }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
      <div class="pag">
        {% include "pagination.html" with page=page %}
      </div>
    </div>
  {% else %}
    <div class="container">
      <h1>Filmdatenbank</h1>
    </div>
  {% endif %}
{% endblock %}

verwaltung/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>
        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}">Next</a>
        {% endif %}
    </span>
</div>

verwaltung/templates/verwaltung/film_confirm_delete.html
{% extends "base.html" %}
{% block oben %}
<style>
  .mydel{
    margin-top: 30px;
  }
  .myp{
    font-size: 1.3em;
  }
</style>
{% endblock %}
{% block content %}
<div class="container mydel">
  <form action="" method="post">
		{% csrf_token %}
    <p class="myp">Möchten Sie den Film "{{ film.titel }}" aus der Kategorie "{{ film.genre }}" wirklich löschen?</p>
    <input class='btn btn-danger' type="submit" value="Löschen">
  </form>
</div>
{% endblock %}

verwaltung/templates/verwaltung/film_detail.html
{% extends 'base.html' %}
{% block oben %}
  <style>
    .mydetail{
      margin-top: 40px;
    }
  </style>
{% endblock %}
{% block content %}
<div class="container mydetail">
  <h1>{{ film.titel }}</h1>
  <p>Bewertung: {{ film.bew }}</p>
  <p>Genre: {{ film.genre }}</p>
  <p>Qualitaet: {{ film.qual }}</p>
  <p>Ort: {{ film.ort }}</p>
  {% if user.is_authenticated %}
    <a class="btn btn-secondary" href="{% url 'verwaltung:film_edit' pk=film.pk %}">Bearbeiten</a>
    <a class="btn btn-danger" href="{% url 'verwaltung:film_remove' pk=film.pk %}">Löschen</a>
  {% endif %}
</div>
{% endblock %}

verwaltung/templates/verwaltung/film_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block oben %}
<style>
  .myform{
    margin-top: 40px;
  }
</style>
{% endblock %}
{% block content %}
<div class="container myform">
  <form method="POST" id="filmForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit">Speichern</button>
  </form>
</div>
{% endblock %}